### ISSUE TITLE
No traits defined on maxminddb::geoip2::City

### ISSUE THREAD

**Issue by GitSquared** [oschwald/maxminddb-rust#12]
Hi,
I'm getting compiler errors telling me that "`the trait 'serde::ser::Serialize' is not implemented for 'maxminddb::geoip2::City'`" when trying to serialize a City type with `serde_json`.

Upon closer inspections, it seems that my City doesn't have any traits implemented.

I'm using:
`rustc 1.27.2`
`maxminddb 0.9.0`
`serde_json 1.0.24`

Any idea what is going on?

**Comment by oschwald** [comment]
#11 should fix this. I haven't done a release yet as I was hoping to tweak #10 a bit and merge it first.

**Comment by GitSquared** [comment]
Ho, thanks for the quick reply.
Yeah, i did a little digging in your code and found that it was implemented so i figured out there was something wrong somewhere. Turns out it's not yet released then.

Any ETA on that release?

**Comment by GitSquared** [comment]
@oschwald Do you plan/expect to make the release/finish work on #10 soon? Sorry to disturb you again, but i could really use this feature.

**Comment by oschwald** [comment]
@GitSquared, thanks for the reminder. I went ahead and did a release without #10 for now.

**Comment by GitSquared** [comment]
@oschwald Thanks!
