### ISSUE TITLE
Taking ownership of Vec<u8>, unsafe usage in open_readfile

### ISSUE THREAD

**Issue by kpcyrd** [oschwald/maxminddb-rust#17]
#15 Made a change that allows creating a reader by transferring ownership of an Vec<u8> into the reader. This was changed in #16 and introduced some unsafe code into `open_readfile`, which we should try to get rid of.

It makes sense that unsafe code is needed for an mmap, but it shouldn't be used to simply load a file into memory. If we re-introduce a way to transfer a Vec into the reader we could just use that to read from disk without any unsafe code.

We might be able to use Cow for this.

**Comment by kpcyrd** [comment]
@oschwald @moschroe I have to versions ready, both of them work for my usecase, support mmap and have reduced unsafe calls to the minimum of one call.

The first one explicitly supports `Vec<u8>` and `Mmap`, the second one accepts anything that implements `AsRef<[u8]>` but requires some changes to the public api for that reason (Reader::open needs to be replaced with the explicit method that should be used due to return types).

Please let me know which one works best for you and I can prepare a PR (also I need some sleep and then review my commits again).

**Comment by moschroe** [comment]
A sketch of both new APIs would be illuminating, I can't image how exactly they might look. Though, as long as unnecessary copies/IO can be avoided, any solution ought to do fine.

**Comment by kpcyrd** [comment]
I've pushed both branches:

Enum: https://github.com/kpcyrd/maxminddb-rust/commit/d06159e1b9965cd1f68fcf0c70dc77651e014aed
Generics: https://github.com/kpcyrd/maxminddb-rust/commit/4a00b312ec07299c4a52ef9b3f59142826ec20fc

**Comment by moschroe** [comment]
I'm a fan of the generics version. It feels more "zero cost" than having an enum requiring branching under the hood.

At the moment, there are two choices, without mmap and with mmap. Explicitly opting in the latter only makes sense if the code path actually gets exercised, so there ought to be reasons for that choice, most likely performance-related. Thus, I propose to let the compiler do away with any unneeded parts.

**Comment by oschwald** [comment]
Thanks for preparing these! I think I might also prefer the generics version. It seems a little cleaner.

**Comment by oschwald** [comment]
@kpcyrd, do you think you will be able to submit a PR with the changes?
