### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by mre** [oschwald/maxminddb-rust#22]
Hey @oschwald,

thanks for this crate.
I made a few benchmarks using [criterion](https://github.com/bheisler/criterion.rs) and the results can be found over [here](https://github.com/mre/maxminddb-rust-bench). If you like, you can copy over the files to your repository.

Bottom line is that maxminddb-rust is quite fast with 30.000 lookups/s on my machine (Macbook Pro 2015, 16GB RAM).
With rayon it goes all the way up to 100.000 lookups/s.

**Comment by oschwald** [comment]
Nice! Thanks.

There is probably a lot of room for improvement in performance. The Go reader, for instance, does about 140k GeoLite2 City lookups per second in a single thread on my machine when decoding to a City struct. Most of the code in this repo was written years before Rust hit 1.0 and I am sure there are quite a few simple optimizations that could be done.
