### ISSUE TITLE
Switch to Serde

### ISSUE THREAD

**Issue by oschwald** [oschwald/maxminddb-rust#3]
Currently `rustc_serialize` is used internally.

**Comment by dtolnay** [comment]
This would be a good time, as rustc-serialize has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by oschwald** [comment]
Thanks for the reminder. I am a bit busy at the moment, but this is something that I'd like to get to. PRs are definitely welcome, if you are so inclined.
