### ISSUE TITLE
lookup fails on private IP address

### ISSUE THREAD

**Issue by Mr-Click** [oschwald/maxminddb-rust#32]
Hi,

when I lookup a private address I get the main thread to panic, here is an example

`fn main() {`
`let reader = maxminddb::Reader::open_readfile("./GeoIP2-ISP.mmdb").unwrap()`
`let isp: geoip2::Isp = reader.lookup("127.0.0.1").unwrap;`
`}`

If I run this code I get

`thread 'main' panicked at 'called Result::unwrap() on an Err value: AddressNotFoundError("Address not found in database")', src/libcore/result.rs:999:5
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.
`

**Comment by oschwald** [comment]
You need to handle the `AddressNotFoundError` error properly rather than just calling unwrap on the result.
