### ISSUE TITLE
InvalidDatabaseError: Unknown data type: 120

### ISSUE THREAD

**Issue by Marwes-Imperva** [oschwald/maxminddb-rust#45]
Downloading the newest version of maxmind's GeoIP2-ISP database gives the error 'InvalidDatabaseError: Unknown data type: 120' when loaded using this lib. I don't know if you have access to this (can't share it, I think) and it might be a corrupt database that is the issue but I wanted to report it in case anyone has any idea. Going to look into it more myself first on monday.

**Comment by oschwald** [comment]
Thanks, I am able to reproduce this. I tested many of the official readers from MaxMind and all of them seem to work fine. Given this, I am inclined to think it is some sort of bug in this library. I will need to dig into it more.

**Comment by oschwald** [comment]
Thanks for reporting this. It was indeed a bug caused by an incorrect pointer offset when decoding the metadata. I released 0.17.3 with this fix.
