### ISSUE TITLE
Feature request: encoding/writer functionality

### ISSUE THREAD

**Issue by sempervictus** [oschwald/maxminddb-rust#63]
Thanks for writing this - interesting read and implementation.
I'm hoping to find a library to use in some small projects for converting between the various GeoIP formats and updating databases from external sources - any chance writer functionality is planned for the library in supported formats?

**Comment by oschwald** [comment]
There are no plans for writer functionality as part of this library. There is very little code overlap between an MMDB reader and writer.

**Comment by sempervictus** [comment]
Thanks for pinging back, will try to grok implementations from other languages for rewriting in Rust.
