### ISSUE TITLE
Is paid licence supported?

### ISSUE THREAD

**Issue by ollyde** [oschwald/maxminddb-rust#76]
Unfortunately the free version doesn't work with many IPs including IPv6 we see coming down.

We have a paid licence, the paid licence includes a few files and a different format to free. How do we use these files with this?

<img width="430" alt="Screenshot 2024-02-05 at 13 01 11" src="https://github.com/oschwald/maxminddb-rust/assets/6940726/da0d8d16-7947-4dbb-a48e-523ed1a8af84">

**Comment by ollyde** [comment]
For example

```
static GEO_IP_CITY: OnceCell<Reader<Vec<u8>>> = OnceCell::new();

pub async fn setup_geo_ip() -> Result<(), Error> {
    let reader_city = maxminddb::Reader::open_readfile("./GeoLite2-City.mmdb").map_err(
        |e: maxminddb::MaxMindDBError| {
            Error::msg(format!(
                "Error reading file GeoLite2-City.mmdb, error: {0:?}",
                e
            ))
        },
    )?;

    GEO_IP_CITY
        .set(reader_city)
        .map_err(|_| Error::msg("Error setting GEO_IP_CITY"))?;

    Ok(())
}
```

**Comment by ollyde** [comment]
I figured out how to download the paid version as mmdb but IPv6 still fails

https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-City&suffix=tar.gz&license_key=[your_key]

**Comment by ollyde** [comment]
We make the request like so, using Salvo


This seems to break with IPv6


pub fn get_location(req: &Request) -> Result<Location, ApiError> {
    let mut ip = req.remote_addr().to_string();

    if ip.contains("127.0.0.1") {
        ip = "45.88.221.137".to_string();
        // ip = "2606:2800:220:1:248:1893:25c8:1946".to_string(); // Is a valid IP from Cali
    }

    let ip_address: IpAddr = match FromStr::from_str(&ip) {
        Ok(ip) => ip,
        Err(_) => {
            eprintln!("Error parsing ip: {0:?}", ip);
            return Err(ApiError {
                message: "Error parsing ip".to_string(),
                status: "error-with-ip".to_string(),
            });
        }
    };

    let reader = match GEO_IP_CITY.get() {
        Some(reader) => reader,
        None => {
            eprintln!("Error getting GEO_IP_CITY not setup");
            return Err(ApiError {
                message: "GEO_IP_CITY not setup".to_string(),
                status: "error-with-ip".to_string(),
            });
        }
    };

    let result: geoip2::City = reader.lookup(ip_address).unwrap();

**Comment by ollyde** [comment]
It's logged here as well; not sure which is official Geo IP2 create.

https://github.com/IncSW/geoip2-rs/issues/3

**Comment by oschwald** [comment]
I am not sure what the exact question is, but paid database versions (and third-party MMDB files) are supported as is IPv6.

The IP in your example appears to only have country-level data. I am not sure if that is related to your question. You may have better luck with MaxMind support.

**Comment by ollyde** [comment]
@oschwald what do you mean I only have country level data? It says geoip2::City? 

And I'm loading the city list?

**Comment by oschwald** [comment]
Not all locations in the City database have city-level data. Some IP addresses cannot be geolocated to a particular city.

**Comment by ollyde** [comment]
@oschwald 

Using the paid download MMDB.

Their IP address tester for GeoIP it shows that this is a valid IP. 2606:2800:220:1:248:1893:25c8:1946

And using the NodeJS API it works, so I'm pretty sure there's an issue with this lib ;-)

<img width="1063" alt="Screenshot 2024-02-05 at 15 40 17" src="https://github.com/oschwald/maxminddb-rust/assets/6940726/bd141aa9-0ecf-4283-a04b-538225598c11">

**Comment by oschwald** [comment]
That screenshot shows there is only country-level data. The location is "United States (US), North America". There is no city or region.

**Comment by ollyde** [comment]
@oschwald ah it's just the Rust is handling errors better... hah thanks
