### ISSUE TITLE
Do you support Detect Proxy Users?

### ISSUE THREAD

**Issue by ymwjbxxq** [oschwald/maxminddb-rust#78]
Hello, 

I hope this message finds you well. I was wondering if you support the https://www.maxmind.com/en/solutions/proxy-vpn-fraud-detection database. If you do, please let me know how. And if not, would it be possible for me to use the same library? 

Thank you kindly, 

Daniele

**Comment by oschwald** [comment]
I am not sure which database you are asking about. If you are referring to MaxMind's Anonymous IP database, yes, this reader will work with that. It should work with any database in the MMDB format.
