### ISSUE TITLE
Add support for IPinfo MMDBs

### ISSUE THREAD

**Issue by GyulyVGC** [oschwald/maxminddb-rust#82]
This library currently only supports **GeoLite2** databases, but it'd be amazing to also support **IPinfo MMDBs**.

[IPinfo](https://ipinfo.io) is one of the leaders in this sector and their data are the most complete and accurate out there.
Many companies already rely on their data, making IPinfo the **most popular provider** of IP address data.

Problem is that instead of representing data as nested structures (like done by GeoLite2) they use a **flat tabular structure**.
A really good article about **differences between the two schemas** can be found [here](https://ipinfo.io/blog/migrating-from-maxmind-to-ipinfo/).

IPinfo claims that their structure allows lookups that are **2.5 times faster** than GeoLite2 lookups, and I think this is a further reason to support reading data from their DBs.

**Comment by oschwald** [comment]
This library should support any valid MMDB file. If there is a file within the specification that does not work with this library, I would be happy to look at it and try to fix any issues.

However, I assume you are actually referring to providing model structs for the IPinfo record format. These would be better in a separate package maintained by someone else. I am not interested in adding them or maintaining them in this crate. In fact, I think it was a mistake that the GeoIP2/GeoLite2 structs were included here in the first place. This is a general purpose library that can decode a record to an arbitrary struct that implements `Deserialize`. I don't use the included structs with this library or the similar Go library and instead tend to use structs with the minimal data that I want to look up.

> IPinfo claims that their structure allows lookups that are 2.5 times faster than GeoLite2 lookups, and I think this is a further reason to support reading data from their DBs.

This sounds like an unfounded marketing claim. The nested structure does not significantly impact decoding performance. A map in the database is essentially just a byte or two that says the next X records are in the map. Decoding it has very little overhead and can provide some performance benefits (e.g., when doing partial decoding or  if caching is implemented).

The primary costs of doing a lookup are (1) tree depth and (2) the amount of data in a record. A database with more specific data for each IP address will have greater tree depth. In terms of record size, the IPinfo records do seem to have a lot less data, e.g., no localized names.

From the video on the page you link to, the "2.5 times slower" claim seem to be based entirely on the lookup performance of a single IP address, `8.8.8.8`, using the pure Python MMDB reader.
